<template><div><h2 id="一、简介" tabindex="-1"><a class="header-anchor" href="#一、简介" aria-hidden="true">#</a> 一、简介</h2>
<p>在idea的插件市场搜素easycode安装之后把下面的模版复制到Settings &gt; Other Settings &gt; EasyCode-MybagisCodeHelper即可。</p>
<p>模版依赖lombok，需要先安装lombok插件和maven依赖tkmybatis。</p>
<h2 id="二、配置模版" tabindex="-1"><a class="header-anchor" href="#二、配置模版" aria-hidden="true">#</a> 二、配置模版</h2>
<h3 id="_2-1-entity" tabindex="-1"><a class="header-anchor" href="#_2-1-entity" aria-hidden="true">#</a> 2.1 entity</h3>
<div class="language-groovy line-numbers-mode" data-ext="groovy"><pre v-pre class="language-groovy"><code>##定义初始变量
<span class="token punctuation">$</span><span class="token operator">!</span>init
#<span class="token function">set</span><span class="token punctuation">(</span><span class="token punctuation">$</span>tableName <span class="token operator">=</span> <span class="token punctuation">$</span>tool<span class="token punctuation">.</span><span class="token function">append</span><span class="token punctuation">(</span><span class="token punctuation">$</span>tableInfo<span class="token punctuation">.</span>name<span class="token punctuation">,</span> <span class="token interpolation-string"><span class="token string">"Entity"</span></span><span class="token punctuation">)</span><span class="token punctuation">)</span>
##设置回调
<span class="token punctuation">$</span><span class="token operator">!</span>callback<span class="token punctuation">.</span><span class="token function">setFileName</span><span class="token punctuation">(</span><span class="token punctuation">$</span>tool<span class="token punctuation">.</span><span class="token function">append</span><span class="token punctuation">(</span><span class="token punctuation">$</span>tableName<span class="token punctuation">,</span> <span class="token interpolation-string"><span class="token string">".java"</span></span><span class="token punctuation">)</span><span class="token punctuation">)</span>
<span class="token punctuation">$</span><span class="token operator">!</span>callback<span class="token punctuation">.</span><span class="token function">setSavePath</span><span class="token punctuation">(</span><span class="token punctuation">$</span>tool<span class="token punctuation">.</span><span class="token function">append</span><span class="token punctuation">(</span><span class="token punctuation">$</span>tableInfo<span class="token punctuation">.</span>savePath<span class="token punctuation">,</span> <span class="token interpolation-string"><span class="token string">"/model/entity"</span></span><span class="token punctuation">)</span><span class="token punctuation">)</span>

##拿到主键
#<span class="token keyword">if</span><span class="token punctuation">(</span><span class="token operator">!</span><span class="token punctuation">$</span>tableInfo<span class="token punctuation">.</span>pkColumn<span class="token punctuation">.</span><span class="token function">isEmpty</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
    #<span class="token function">set</span><span class="token punctuation">(</span><span class="token punctuation">$</span>pk <span class="token operator">=</span> <span class="token punctuation">$</span>tableInfo<span class="token punctuation">.</span>pkColumn<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
#end

##使用全局变量实现默认包导入
<span class="token keyword">package</span> <span class="token punctuation">$</span><span class="token operator">!</span><span class="token punctuation">{</span>tableInfo<span class="token punctuation">.</span>savePackageName<span class="token punctuation">}</span><span class="token punctuation">.</span>model<span class="token punctuation">.</span>entity<span class="token punctuation">;</span>

<span class="token keyword">import</span> java<span class="token punctuation">.</span>io<span class="token punctuation">.</span>Serializable<span class="token punctuation">;</span>
<span class="token keyword">import</span> lombok<span class="token punctuation">.</span>AllArgsConstructor<span class="token punctuation">;</span>
<span class="token keyword">import</span> lombok<span class="token punctuation">.</span>Builder<span class="token punctuation">;</span>
<span class="token keyword">import</span> lombok<span class="token punctuation">.</span>Data<span class="token punctuation">;</span>
<span class="token keyword">import</span> lombok<span class="token punctuation">.</span>NoArgsConstructor<span class="token punctuation">;</span>
<span class="token keyword">import</span> javax<span class="token punctuation">.</span>persistence<span class="token punctuation">.</span>*<span class="token punctuation">;</span>
<span class="token punctuation">$</span><span class="token operator">!</span>autoImport
##使用宏定义实现类注释信息
<span class="token comment">/**
 * $!{tableInfo.comment}($!{tableInfo.name})实体类
 *
 * @author $!author
 * @since $!time.currTime()
 */</span>

<span class="token annotation punctuation">@Data</span>
<span class="token annotation punctuation">@Builder</span>
<span class="token annotation punctuation">@AllArgsConstructor</span>
<span class="token annotation punctuation">@NoArgsConstructor</span>
<span class="token annotation punctuation">@Table</span><span class="token punctuation">(</span>name <span class="token operator">=</span> <span class="token interpolation-string"><span class="token string">"</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">$</span><span class="token expression">tableInfo</span></span><span class="token string">.obj.getName()"</span></span><span class="token punctuation">)</span>
<span class="token keyword">public</span> <span class="token keyword">class</span> <span class="token punctuation">$</span><span class="token operator">!</span><span class="token punctuation">{</span>tableInfo<span class="token punctuation">.</span>name<span class="token punctuation">}</span>Entity <span class="token keyword">implements</span> <span class="token class-name">Serializable</span> <span class="token punctuation">{</span>

    <span class="token keyword">private</span> <span class="token keyword">static</span> <span class="token keyword">final</span> <span class="token keyword">long</span> serialVersionUID <span class="token operator">=</span> <span class="token punctuation">$</span><span class="token operator">!</span>tool<span class="token punctuation">.</span><span class="token function">serial</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
#<span class="token function">foreach</span><span class="token punctuation">(</span><span class="token punctuation">$</span>column <span class="token keyword">in</span> <span class="token punctuation">$</span>tableInfo<span class="token punctuation">.</span>fullColumn<span class="token punctuation">)</span>
#<span class="token keyword">if</span><span class="token punctuation">(</span><span class="token punctuation">$</span><span class="token punctuation">{</span>velocityCount<span class="token punctuation">}</span> <span class="token operator">==</span>  <span class="token number">1</span><span class="token punctuation">)</span>
#end
#<span class="token keyword">if</span><span class="token punctuation">(</span><span class="token punctuation">$</span><span class="token punctuation">{</span>column<span class="token punctuation">.</span>comment<span class="token punctuation">}</span><span class="token punctuation">)</span>

    <span class="token comment">/**
     * ${column.comment}
     */</span>
#end
#<span class="token keyword">if</span><span class="token punctuation">(</span><span class="token punctuation">$</span><span class="token punctuation">{</span>velocityCount<span class="token punctuation">}</span> <span class="token operator">==</span>  <span class="token number">1</span><span class="token punctuation">)</span>
    <span class="token annotation punctuation">@Id</span>
    <span class="token annotation punctuation">@Column</span><span class="token punctuation">(</span>name <span class="token operator">=</span> <span class="token interpolation-string"><span class="token string">"</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">$</span><span class="token expression">column</span></span><span class="token string">.obj.getName()"</span></span><span class="token punctuation">)</span>
#<span class="token keyword">else</span>
    <span class="token annotation punctuation">@Column</span><span class="token punctuation">(</span>name <span class="token operator">=</span> <span class="token interpolation-string"><span class="token string">"</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">$</span><span class="token expression">column</span></span><span class="token string">.obj.getName()"</span></span><span class="token punctuation">)</span>
#end
    <span class="token keyword">private</span> <span class="token punctuation">$</span><span class="token operator">!</span><span class="token punctuation">{</span>tool<span class="token punctuation">.</span><span class="token function">getClsNameByFullName</span><span class="token punctuation">(</span><span class="token punctuation">$</span>column<span class="token punctuation">.</span>type<span class="token punctuation">)</span><span class="token punctuation">}</span> <span class="token punctuation">$</span><span class="token operator">!</span><span class="token punctuation">{</span>column<span class="token punctuation">.</span>name<span class="token punctuation">}</span><span class="token punctuation">;</span>
#end
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_2-2-xml" tabindex="-1"><a class="header-anchor" href="#_2-2-xml" aria-hidden="true">#</a> 2.2 xml</h3>
<div class="language-groovy line-numbers-mode" data-ext="groovy"><pre v-pre class="language-groovy"><code>##引入mybatis支持
<span class="token punctuation">$</span><span class="token operator">!</span>mybatisSupport
<span class="token punctuation">$</span><span class="token operator">!</span>init
##设置保存名称与保存位置
<span class="token punctuation">$</span><span class="token operator">!</span>callback<span class="token punctuation">.</span><span class="token function">setFileName</span><span class="token punctuation">(</span><span class="token punctuation">$</span>tool<span class="token punctuation">.</span><span class="token function">append</span><span class="token punctuation">(</span><span class="token punctuation">$</span><span class="token operator">!</span><span class="token punctuation">{</span>tableInfo<span class="token punctuation">.</span>name<span class="token punctuation">}</span><span class="token punctuation">,</span> <span class="token interpolation-string"><span class="token string">"Mapper.xml"</span></span><span class="token punctuation">)</span><span class="token punctuation">)</span>
<span class="token punctuation">$</span><span class="token operator">!</span>callback<span class="token punctuation">.</span><span class="token function">setSavePath</span><span class="token punctuation">(</span><span class="token punctuation">$</span>tool<span class="token punctuation">.</span><span class="token function">append</span><span class="token punctuation">(</span><span class="token punctuation">$</span>tableInfo<span class="token punctuation">.</span>savePath<span class="token punctuation">,</span> <span class="token interpolation-string"><span class="token string">"/dao/xml"</span></span><span class="token punctuation">)</span><span class="token punctuation">)</span>


##拿到主键
#<span class="token keyword">if</span><span class="token punctuation">(</span><span class="token operator">!</span><span class="token punctuation">$</span>tableInfo<span class="token punctuation">.</span>pkColumn<span class="token punctuation">.</span><span class="token function">isEmpty</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
    #<span class="token function">set</span><span class="token punctuation">(</span><span class="token punctuation">$</span>pk <span class="token operator">=</span> <span class="token punctuation">$</span>tableInfo<span class="token punctuation">.</span>pkColumn<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
#end

<span class="token operator">&lt;</span><span class="token operator">?</span>xml version<span class="token operator">=</span><span class="token interpolation-string"><span class="token string">"1.0"</span></span> encoding<span class="token operator">=</span><span class="token interpolation-string"><span class="token string">"UTF-8"</span></span><span class="token operator">?</span><span class="token operator">></span>
<span class="token operator">&lt;</span><span class="token operator">!</span>DOCTYPE mapper PUBLIC <span class="token interpolation-string"><span class="token string">"-//mybatis.org//DTD Mapper 3.0//EN"</span></span> <span class="token interpolation-string"><span class="token string">"http://mybatis.org/dtd/mybatis-3-mapper.dtd"</span></span><span class="token operator">></span>
<span class="token operator">&lt;</span>mapper namespace<span class="token operator">=</span><span class="token interpolation-string"><span class="token string">"$!{tableInfo.savePackageName}.dao.$!{tableInfo.name}Mapper"</span></span><span class="token operator">></span>

    <span class="token operator">&lt;</span>resultMap id<span class="token operator">=</span><span class="token interpolation-string"><span class="token string">"BaseResultMap"</span></span> type<span class="token operator">=</span><span class="token interpolation-string"><span class="token string">"$!{tableInfo.savePackageName}.model.entity.$!{tableInfo.name}Entity"</span></span><span class="token operator">></span>
        <span class="token operator">&lt;</span><span class="token operator">!</span><span class="token operator">--</span><span class="token annotation punctuation">@Table</span> <span class="token punctuation">$</span><span class="token operator">!</span><span class="token punctuation">{</span>tableInfo<span class="token punctuation">.</span>originTableName<span class="token punctuation">}</span><span class="token operator">--</span><span class="token operator">></span>
#<span class="token function">foreach</span><span class="token punctuation">(</span><span class="token punctuation">$</span>column <span class="token keyword">in</span> <span class="token punctuation">$</span>tableInfo<span class="token punctuation">.</span>fullColumn<span class="token punctuation">)</span>
        <span class="token operator">&lt;</span>result property<span class="token operator">=</span><span class="token interpolation-string"><span class="token string">"$!column.name"</span></span> column<span class="token operator">=</span><span class="token interpolation-string"><span class="token string">"$!column.obj.name"</span></span> jdbcType<span class="token operator">=</span><span class="token interpolation-string"><span class="token string">"$!column.ext.jdbcType"</span></span><span class="token operator">/</span><span class="token operator">></span>
#end
    <span class="token operator">&lt;</span><span class="token operator">/</span>resultMap<span class="token operator">></span>

<span class="token operator">&lt;</span><span class="token operator">/</span>mapper<span class="token operator">></span>

</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_2-3-mapper" tabindex="-1"><a class="header-anchor" href="#_2-3-mapper" aria-hidden="true">#</a> 2.3 mapper</h3>
<div class="language-groovy line-numbers-mode" data-ext="groovy"><pre v-pre class="language-groovy"><code>
##定义初始变量
<span class="token punctuation">$</span><span class="token operator">!</span>init
#<span class="token function">set</span><span class="token punctuation">(</span><span class="token punctuation">$</span>tableName <span class="token operator">=</span> <span class="token punctuation">$</span>tool<span class="token punctuation">.</span><span class="token function">append</span><span class="token punctuation">(</span><span class="token punctuation">$</span>tableInfo<span class="token punctuation">.</span>name<span class="token punctuation">,</span> <span class="token interpolation-string"><span class="token string">"Mapper"</span></span><span class="token punctuation">)</span><span class="token punctuation">)</span>
##设置回调
<span class="token punctuation">$</span><span class="token operator">!</span>callback<span class="token punctuation">.</span><span class="token function">setFileName</span><span class="token punctuation">(</span><span class="token punctuation">$</span>tool<span class="token punctuation">.</span><span class="token function">append</span><span class="token punctuation">(</span><span class="token punctuation">$</span>tableName<span class="token punctuation">,</span> <span class="token interpolation-string"><span class="token string">".java"</span></span><span class="token punctuation">)</span><span class="token punctuation">)</span>
<span class="token punctuation">$</span><span class="token operator">!</span>callback<span class="token punctuation">.</span><span class="token function">setSavePath</span><span class="token punctuation">(</span><span class="token punctuation">$</span>tool<span class="token punctuation">.</span><span class="token function">append</span><span class="token punctuation">(</span><span class="token punctuation">$</span>tableInfo<span class="token punctuation">.</span>savePath<span class="token punctuation">,</span> <span class="token interpolation-string"><span class="token string">"/dao"</span></span><span class="token punctuation">)</span><span class="token punctuation">)</span>

##拿到主键
#<span class="token keyword">if</span><span class="token punctuation">(</span><span class="token operator">!</span><span class="token punctuation">$</span>tableInfo<span class="token punctuation">.</span>pkColumn<span class="token punctuation">.</span><span class="token function">isEmpty</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
    #<span class="token function">set</span><span class="token punctuation">(</span><span class="token punctuation">$</span>pk <span class="token operator">=</span> <span class="token punctuation">$</span>tableInfo<span class="token punctuation">.</span>pkColumn<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
#end

#<span class="token keyword">if</span><span class="token punctuation">(</span><span class="token punctuation">$</span>tableInfo<span class="token punctuation">.</span>savePackageName<span class="token punctuation">)</span><span class="token keyword">package</span> <span class="token punctuation">$</span><span class="token operator">!</span><span class="token punctuation">{</span>tableInfo<span class="token punctuation">.</span>savePackageName<span class="token punctuation">}</span><span class="token punctuation">.</span>#<span class="token punctuation">{</span>end<span class="token punctuation">}</span>dao<span class="token punctuation">;</span>

<span class="token keyword">import</span> <span class="token punctuation">$</span><span class="token operator">!</span><span class="token punctuation">{</span>tableInfo<span class="token punctuation">.</span>savePackageName<span class="token punctuation">}</span><span class="token punctuation">.</span>model<span class="token punctuation">.</span>entity<span class="token punctuation">.</span><span class="token punctuation">$</span><span class="token operator">!</span><span class="token punctuation">{</span>tableInfo<span class="token punctuation">.</span>name<span class="token punctuation">}</span>Entity<span class="token punctuation">;</span>
<span class="token keyword">import</span> tk<span class="token punctuation">.</span>mybatis<span class="token punctuation">.</span>mapper<span class="token punctuation">.</span>common<span class="token punctuation">.</span>Mapper<span class="token punctuation">;</span>

<span class="token comment">/**
 * $!{tableInfo.comment}($!{tableInfo.name})表数据库访问层
 *
 * @author $!author
 * @since $!time.currTime()
 */</span>
<span class="token keyword">public</span> <span class="token keyword">interface</span> <span class="token punctuation">$</span><span class="token operator">!</span><span class="token punctuation">{</span>tableName<span class="token punctuation">}</span> <span class="token keyword">extends</span> <span class="token class-name">Mapper</span><span class="token operator">&lt;</span><span class="token punctuation">$</span><span class="token operator">!</span><span class="token punctuation">{</span>tableInfo<span class="token punctuation">.</span>name<span class="token punctuation">}</span>Entity<span class="token operator">></span><span class="token punctuation">{</span>

<span class="token punctuation">}</span>

</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_2-4-service" tabindex="-1"><a class="header-anchor" href="#_2-4-service" aria-hidden="true">#</a> 2.4 service</h3>
<div class="language-groovy line-numbers-mode" data-ext="groovy"><pre v-pre class="language-groovy"><code>
##定义初始变量
<span class="token punctuation">$</span><span class="token operator">!</span>init
#<span class="token function">set</span><span class="token punctuation">(</span><span class="token punctuation">$</span>tableName <span class="token operator">=</span> <span class="token punctuation">$</span>tool<span class="token punctuation">.</span><span class="token function">append</span><span class="token punctuation">(</span><span class="token punctuation">$</span>tableInfo<span class="token punctuation">.</span>name<span class="token punctuation">,</span> <span class="token interpolation-string"><span class="token string">"Service"</span></span><span class="token punctuation">)</span><span class="token punctuation">)</span>
##设置回调
<span class="token punctuation">$</span><span class="token operator">!</span>callback<span class="token punctuation">.</span><span class="token function">setFileName</span><span class="token punctuation">(</span><span class="token punctuation">$</span>tool<span class="token punctuation">.</span><span class="token function">append</span><span class="token punctuation">(</span><span class="token punctuation">$</span>tableName<span class="token punctuation">,</span> <span class="token interpolation-string"><span class="token string">".java"</span></span><span class="token punctuation">)</span><span class="token punctuation">)</span>
<span class="token punctuation">$</span><span class="token operator">!</span>callback<span class="token punctuation">.</span><span class="token function">setSavePath</span><span class="token punctuation">(</span><span class="token punctuation">$</span>tool<span class="token punctuation">.</span><span class="token function">append</span><span class="token punctuation">(</span><span class="token punctuation">$</span>tableInfo<span class="token punctuation">.</span>savePath<span class="token punctuation">,</span> <span class="token interpolation-string"><span class="token string">"/service"</span></span><span class="token punctuation">)</span><span class="token punctuation">)</span>

##拿到主键
#<span class="token keyword">if</span><span class="token punctuation">(</span><span class="token operator">!</span><span class="token punctuation">$</span>tableInfo<span class="token punctuation">.</span>pkColumn<span class="token punctuation">.</span><span class="token function">isEmpty</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
    #<span class="token function">set</span><span class="token punctuation">(</span><span class="token punctuation">$</span>pk <span class="token operator">=</span> <span class="token punctuation">$</span>tableInfo<span class="token punctuation">.</span>pkColumn<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
#end

#<span class="token keyword">if</span><span class="token punctuation">(</span><span class="token punctuation">$</span>tableInfo<span class="token punctuation">.</span>savePackageName<span class="token punctuation">)</span><span class="token keyword">package</span> <span class="token punctuation">$</span><span class="token operator">!</span><span class="token punctuation">{</span>tableInfo<span class="token punctuation">.</span>savePackageName<span class="token punctuation">}</span><span class="token punctuation">.</span>#<span class="token punctuation">{</span>end<span class="token punctuation">}</span>service<span class="token punctuation">;</span>

<span class="token comment">/**
 * $!{tableInfo.comment}($!{tableInfo.name})表服务接口
 *
 * @author $!author
 * @since $!time.currTime()
 */</span>
<span class="token keyword">public</span> <span class="token keyword">interface</span> <span class="token punctuation">$</span><span class="token operator">!</span><span class="token punctuation">{</span>tableName<span class="token punctuation">}</span> <span class="token punctuation">{</span>

<span class="token punctuation">}</span>

</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_2-5-serviceimpl" tabindex="-1"><a class="header-anchor" href="#_2-5-serviceimpl" aria-hidden="true">#</a> 2.5 serviceimpl</h3>
<div class="language-groovy line-numbers-mode" data-ext="groovy"><pre v-pre class="language-groovy"><code>
##定义初始变量
<span class="token punctuation">$</span><span class="token operator">!</span>init
#<span class="token function">set</span><span class="token punctuation">(</span><span class="token punctuation">$</span>tableName <span class="token operator">=</span> <span class="token punctuation">$</span>tool<span class="token punctuation">.</span><span class="token function">append</span><span class="token punctuation">(</span><span class="token punctuation">$</span>tableInfo<span class="token punctuation">.</span>name<span class="token punctuation">,</span> <span class="token interpolation-string"><span class="token string">"ServiceImpl"</span></span><span class="token punctuation">)</span><span class="token punctuation">)</span>
##设置回调
<span class="token punctuation">$</span><span class="token operator">!</span>callback<span class="token punctuation">.</span><span class="token function">setFileName</span><span class="token punctuation">(</span><span class="token punctuation">$</span>tool<span class="token punctuation">.</span><span class="token function">append</span><span class="token punctuation">(</span><span class="token punctuation">$</span>tableName<span class="token punctuation">,</span> <span class="token interpolation-string"><span class="token string">".java"</span></span><span class="token punctuation">)</span><span class="token punctuation">)</span>
<span class="token punctuation">$</span><span class="token operator">!</span>callback<span class="token punctuation">.</span><span class="token function">setSavePath</span><span class="token punctuation">(</span><span class="token punctuation">$</span>tool<span class="token punctuation">.</span><span class="token function">append</span><span class="token punctuation">(</span><span class="token punctuation">$</span>tableInfo<span class="token punctuation">.</span>savePath<span class="token punctuation">,</span> <span class="token interpolation-string"><span class="token string">"/service/impl"</span></span><span class="token punctuation">)</span><span class="token punctuation">)</span>

##拿到主键
#<span class="token keyword">if</span><span class="token punctuation">(</span><span class="token operator">!</span><span class="token punctuation">$</span>tableInfo<span class="token punctuation">.</span>pkColumn<span class="token punctuation">.</span><span class="token function">isEmpty</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
    #<span class="token function">set</span><span class="token punctuation">(</span><span class="token punctuation">$</span>pk <span class="token operator">=</span> <span class="token punctuation">$</span>tableInfo<span class="token punctuation">.</span>pkColumn<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
#end

#<span class="token keyword">if</span><span class="token punctuation">(</span><span class="token punctuation">$</span>tableInfo<span class="token punctuation">.</span>savePackageName<span class="token punctuation">)</span><span class="token keyword">package</span> <span class="token punctuation">$</span><span class="token operator">!</span><span class="token punctuation">{</span>tableInfo<span class="token punctuation">.</span>savePackageName<span class="token punctuation">}</span><span class="token punctuation">.</span>#<span class="token punctuation">{</span>end<span class="token punctuation">}</span>service<span class="token punctuation">.</span>impl<span class="token punctuation">;</span>

<span class="token keyword">import</span> <span class="token punctuation">$</span><span class="token operator">!</span><span class="token punctuation">{</span>tableInfo<span class="token punctuation">.</span>savePackageName<span class="token punctuation">}</span><span class="token punctuation">.</span>dms<span class="token punctuation">.</span><span class="token punctuation">$</span><span class="token operator">!</span><span class="token punctuation">{</span>tableInfo<span class="token punctuation">.</span>name<span class="token punctuation">}</span>Dms<span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token punctuation">$</span><span class="token operator">!</span><span class="token punctuation">{</span>tableInfo<span class="token punctuation">.</span>savePackageName<span class="token punctuation">}</span><span class="token punctuation">.</span>service<span class="token punctuation">.</span><span class="token punctuation">$</span><span class="token operator">!</span><span class="token punctuation">{</span>tableInfo<span class="token punctuation">.</span>name<span class="token punctuation">}</span>Service<span class="token punctuation">;</span>
<span class="token keyword">import</span> org<span class="token punctuation">.</span>springframework<span class="token punctuation">.</span>stereotype<span class="token punctuation">.</span>Service<span class="token punctuation">;</span>
<span class="token keyword">import</span> lombok<span class="token punctuation">.</span>AllArgsConstructor<span class="token punctuation">;</span>
<span class="token keyword">import</span> lombok<span class="token punctuation">.</span>extern<span class="token punctuation">.</span>slf4j<span class="token punctuation">.</span>Slf4j<span class="token punctuation">;</span>

<span class="token comment">/**
 * $!{tableInfo.comment}($!{tableInfo.name})表服务实现类
 *
 * @author $!author
 * @since $!time.currTime()
 */</span>
<span class="token annotation punctuation">@Service</span><span class="token punctuation">(</span><span class="token interpolation-string"><span class="token string">"$!tool.firstLowerCase($!{tableInfo.name})Service"</span></span><span class="token punctuation">)</span>
<span class="token annotation punctuation">@Slf4j</span>
<span class="token annotation punctuation">@AllArgsConstructor</span>
<span class="token keyword">public</span> <span class="token keyword">class</span> <span class="token punctuation">$</span><span class="token operator">!</span><span class="token punctuation">{</span>tableName<span class="token punctuation">}</span> <span class="token keyword">implements</span> <span class="token punctuation">$</span><span class="token operator">!</span><span class="token punctuation">{</span>tableInfo<span class="token punctuation">.</span>name<span class="token punctuation">}</span>Service <span class="token punctuation">{</span>

    <span class="token keyword">private</span> <span class="token keyword">final</span> <span class="token punctuation">$</span><span class="token operator">!</span><span class="token punctuation">{</span>tableInfo<span class="token punctuation">.</span>name<span class="token punctuation">}</span>Dms <span class="token punctuation">$</span><span class="token operator">!</span>tool<span class="token punctuation">.</span><span class="token function">firstLowerCase</span><span class="token punctuation">(</span><span class="token punctuation">$</span><span class="token operator">!</span><span class="token punctuation">{</span>tableInfo<span class="token punctuation">.</span>name<span class="token punctuation">}</span><span class="token punctuation">)</span>Dms<span class="token punctuation">;</span>

<span class="token punctuation">}</span>

</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_2-6-controller" tabindex="-1"><a class="header-anchor" href="#_2-6-controller" aria-hidden="true">#</a> 2.6 controller</h3>
<div class="language-groovy line-numbers-mode" data-ext="groovy"><pre v-pre class="language-groovy"><code>
##定义初始变量
<span class="token punctuation">$</span><span class="token operator">!</span>init
#<span class="token function">set</span><span class="token punctuation">(</span><span class="token punctuation">$</span>tableName <span class="token operator">=</span> <span class="token punctuation">$</span>tool<span class="token punctuation">.</span><span class="token function">append</span><span class="token punctuation">(</span><span class="token punctuation">$</span>tableInfo<span class="token punctuation">.</span>name<span class="token punctuation">,</span> <span class="token interpolation-string"><span class="token string">"Controller"</span></span><span class="token punctuation">)</span><span class="token punctuation">)</span>
##设置回调
<span class="token punctuation">$</span><span class="token operator">!</span>callback<span class="token punctuation">.</span><span class="token function">setFileName</span><span class="token punctuation">(</span><span class="token punctuation">$</span>tool<span class="token punctuation">.</span><span class="token function">append</span><span class="token punctuation">(</span><span class="token punctuation">$</span>tableName<span class="token punctuation">,</span> <span class="token interpolation-string"><span class="token string">".java"</span></span><span class="token punctuation">)</span><span class="token punctuation">)</span>
<span class="token punctuation">$</span><span class="token operator">!</span>callback<span class="token punctuation">.</span><span class="token function">setSavePath</span><span class="token punctuation">(</span><span class="token punctuation">$</span>tool<span class="token punctuation">.</span><span class="token function">append</span><span class="token punctuation">(</span><span class="token punctuation">$</span>tableInfo<span class="token punctuation">.</span>savePath<span class="token punctuation">,</span> <span class="token interpolation-string"><span class="token string">"/web"</span></span><span class="token punctuation">)</span><span class="token punctuation">)</span>
##拿到主键
#<span class="token keyword">if</span><span class="token punctuation">(</span><span class="token operator">!</span><span class="token punctuation">$</span>tableInfo<span class="token punctuation">.</span>pkColumn<span class="token punctuation">.</span><span class="token function">isEmpty</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
    #<span class="token function">set</span><span class="token punctuation">(</span><span class="token punctuation">$</span>pk <span class="token operator">=</span> <span class="token punctuation">$</span>tableInfo<span class="token punctuation">.</span>pkColumn<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
#end

#<span class="token keyword">if</span><span class="token punctuation">(</span><span class="token punctuation">$</span>tableInfo<span class="token punctuation">.</span>savePackageName<span class="token punctuation">)</span><span class="token keyword">package</span> <span class="token punctuation">$</span><span class="token operator">!</span><span class="token punctuation">{</span>tableInfo<span class="token punctuation">.</span>savePackageName<span class="token punctuation">}</span><span class="token punctuation">.</span>#<span class="token punctuation">{</span>end<span class="token punctuation">}</span>web<span class="token punctuation">;</span>

<span class="token keyword">import</span> <span class="token punctuation">$</span><span class="token operator">!</span><span class="token punctuation">{</span>tableInfo<span class="token punctuation">.</span>savePackageName<span class="token punctuation">}</span><span class="token punctuation">.</span>entity<span class="token punctuation">.</span><span class="token punctuation">$</span><span class="token operator">!</span><span class="token punctuation">{</span>tableInfo<span class="token punctuation">.</span>name<span class="token punctuation">}</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token punctuation">$</span><span class="token operator">!</span><span class="token punctuation">{</span>tableInfo<span class="token punctuation">.</span>savePackageName<span class="token punctuation">}</span><span class="token punctuation">.</span>service<span class="token punctuation">.</span><span class="token punctuation">$</span><span class="token operator">!</span><span class="token punctuation">{</span>tableInfo<span class="token punctuation">.</span>name<span class="token punctuation">}</span>Service<span class="token punctuation">;</span>
<span class="token keyword">import</span> lombok<span class="token punctuation">.</span>AllArgsConstructor<span class="token punctuation">;</span>
<span class="token keyword">import</span> lombok<span class="token punctuation">.</span>extern<span class="token punctuation">.</span>slf4j<span class="token punctuation">.</span>Slf4j<span class="token punctuation">;</span>

<span class="token comment">/**
 * $!{tableInfo.comment}($!{tableInfo.name})表控制层
 *
 * @author $!author
 * @since $!time.currTime()
 */</span>
<span class="token annotation punctuation">@RestController</span>
<span class="token annotation punctuation">@RequestMapping</span><span class="token punctuation">(</span><span class="token interpolation-string"><span class="token string">"$!tool.firstLowerCase(</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">$</span><span class="token expression">tableInfo</span></span><span class="token string">.name)"</span></span><span class="token punctuation">)</span>
<span class="token annotation punctuation">@AllArgsConstructor</span>
<span class="token annotation punctuation">@Slf4j</span>
<span class="token keyword">public</span> <span class="token keyword">class</span> <span class="token punctuation">$</span><span class="token operator">!</span><span class="token punctuation">{</span>tableName<span class="token punctuation">}</span> <span class="token punctuation">{</span>

    <span class="token keyword">private</span> <span class="token keyword">final</span> <span class="token punctuation">$</span><span class="token operator">!</span><span class="token punctuation">{</span>tableInfo<span class="token punctuation">.</span>name<span class="token punctuation">}</span>Service <span class="token punctuation">$</span><span class="token operator">!</span>tool<span class="token punctuation">.</span><span class="token function">firstLowerCase</span><span class="token punctuation">(</span><span class="token punctuation">$</span><span class="token operator">!</span><span class="token punctuation">{</span>tableInfo<span class="token punctuation">.</span>name<span class="token punctuation">}</span><span class="token punctuation">)</span>Service<span class="token punctuation">;</span>

<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


