<template><div><h2 id="一、分类" tabindex="-1"><a class="header-anchor" href="#一、分类" aria-hidden="true">#</a> 一、分类</h2>
<p>1、时间副词：表示时间或频率</p>
<p><img src="https://gaoqisen.github.io/GraphBed/202312/20231217111620.png" alt=""></p>
<p>2、地点副词</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code><span class="token comment">// 表地点</span>
<span class="token function">here</span><span class="token punctuation">(</span>在这里<span class="token punctuation">)</span>，<span class="token function">there</span><span class="token punctuation">(</span>在那里<span class="token punctuation">)</span><span class="token function">home</span><span class="token punctuation">(</span>家<span class="token punctuation">)</span>，<span class="token function">upstairs</span><span class="token punctuation">(</span>在楼上<span class="token punctuation">)</span>，<span class="token function">downstairs</span><span class="token punctuation">(</span>在楼下<span class="token punctuation">)</span>，<span class="token function">anywhere</span><span class="token punctuation">(</span>任何地方<span class="token punctuation">)</span>，<span class="token function">nowhere</span><span class="token punctuation">(</span>无处<span class="token punctuation">)</span>，<span class="token function">somewhere</span><span class="token punctuation">(</span>某个地方<span class="token punctuation">)</span>，<span class="token function">abroad</span><span class="token punctuation">(</span>在国外<span class="token punctuation">)</span>，<span class="token function">elsewhere</span><span class="token punctuation">(</span>在别处<span class="token punctuation">)</span>

<span class="token comment">// 表位置</span>
<span class="token function">above</span><span class="token punctuation">(</span>上文<span class="token punctuation">)</span>，<span class="token function">below</span><span class="token punctuation">(</span>下面<span class="token punctuation">)</span>，<span class="token function">down</span><span class="token punctuation">(</span>在下方<span class="token punctuation">)</span>，<span class="token function">up</span><span class="token punctuation">(</span>在上方<span class="token punctuation">)</span>，<span class="token function">out</span><span class="token punctuation">(</span>向外<span class="token punctuation">)</span>，<span class="token function">in</span><span class="token punctuation">(</span>在里头<span class="token punctuation">)</span>，<span class="token function">across</span><span class="token punctuation">(</span>从一边<span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">.</span>另一边<span class="token punctuation">)</span>，<span class="token function">back</span><span class="token punctuation">(</span>回到原处<span class="token punctuation">)</span>，<span class="token function">along</span><span class="token punctuation">(</span>向前<span class="token punctuation">)</span>，<span class="token function">over</span><span class="token punctuation">(</span>剩下<span class="token punctuation">)</span>，<span class="token function">round</span><span class="token punctuation">(</span>旋转<span class="token punctuation">)</span>，<span class="token function">around</span><span class="token punctuation">(</span>围绕<span class="token punctuation">)</span>，<span class="token function">away</span><span class="token punctuation">(</span>移走<span class="token punctuation">)</span>，<span class="token function">near</span><span class="token punctuation">(</span>在附近<span class="token punctuation">)</span>，<span class="token function">off</span><span class="token punctuation">(</span>离开<span class="token punctuation">)</span>，<span class="token function">on</span><span class="token punctuation">(</span>开着的<span class="token punctuation">)</span>，<span class="token function">inside</span><span class="token punctuation">(</span>内侧<span class="token punctuation">)</span>，<span class="token function">outside</span><span class="token punctuation">(</span>外侧<span class="token punctuation">)</span>，<span class="token function">past</span><span class="token punctuation">(</span>过去的<span class="token punctuation">)</span>

<span class="token class-name">Here</span> is the remains of a mosque <span class="token comment">// 这里是一座清真寺的废墟)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>3、方式副词</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code><span class="token comment">// 方式副词：表示行为方式</span>
<span class="token function">carefully</span><span class="token punctuation">(</span>小心地<span class="token punctuation">)</span>，<span class="token function">properly</span><span class="token punctuation">(</span>正确地<span class="token punctuation">)</span>，<span class="token function">anxiously</span><span class="token punctuation">(</span>不安地<span class="token punctuation">)</span>，<span class="token function">suddenly</span><span class="token punctuation">(</span>突然地<span class="token punctuation">)</span>，<span class="token function">normally</span><span class="token punctuation">(</span>正常地<span class="token punctuation">)</span>，<span class="token function">fast</span><span class="token punctuation">(</span>快速地<span class="token punctuation">)</span>，<span class="token function">calmly</span><span class="token punctuation">(</span>平静地<span class="token punctuation">)</span>，<span class="token function">politely</span><span class="token punctuation">(</span>政治<span class="token punctuation">)</span>，<span class="token function">proudly</span><span class="token punctuation">(</span>自负地<span class="token punctuation">)</span>，<span class="token function">softly</span><span class="token punctuation">(</span>温柔地<span class="token punctuation">)</span>，<span class="token function">warmly</span><span class="token punctuation">(</span>热情地<span class="token punctuation">)</span>，<span class="token function">slowly</span><span class="token punctuation">(</span>缓慢地<span class="token punctuation">)</span>，<span class="token function">badly</span><span class="token punctuation">(</span>父亲<span class="token punctuation">)</span>
<span class="token class-name">Now</span> listen carefully <span class="token comment">// 现在仔细听</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>4、程度副词</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code><span class="token comment">// 程度副词：表示动作程度</span>
<span class="token function">nearly</span><span class="token punctuation">(</span>密切地<span class="token punctuation">)</span>，<span class="token function">rather</span><span class="token punctuation">(</span>相当<span class="token punctuation">)</span>，<span class="token function">very</span><span class="token punctuation">(</span>真正地<span class="token punctuation">)</span>，<span class="token function">too</span><span class="token punctuation">(</span>过于<span class="token punctuation">)</span>，<span class="token function">fully</span><span class="token punctuation">(</span>完全地<span class="token punctuation">)</span>，<span class="token function">almost</span><span class="token punctuation">(</span>差不多<span class="token punctuation">)</span>，<span class="token function">extremely</span><span class="token punctuation">(</span>极度<span class="token punctuation">)</span>，<span class="token function">absolutely</span><span class="token punctuation">(</span>绝对地<span class="token punctuation">)</span>，<span class="token function">slightly</span><span class="token punctuation">(</span>轻微地<span class="token punctuation">)</span>，<span class="token function">simply</span><span class="token punctuation">(</span>简单地<span class="token punctuation">)</span>，<span class="token function">awfully</span><span class="token punctuation">(</span>可怕地<span class="token punctuation">)</span>，<span class="token function">deeply</span><span class="token punctuation">(</span>深刻地<span class="token punctuation">)</span>，<span class="token function">really</span><span class="token punctuation">(</span>真正地<span class="token punctuation">)</span>，<span class="token function">perfectly</span><span class="token punctuation">(</span>完美地<span class="token punctuation">)</span>，<span class="token function">quite</span><span class="token punctuation">(</span>相当<span class="token punctuation">)</span>，<span class="token function">much</span><span class="token punctuation">(</span>非常<span class="token punctuation">)</span>
<span class="token class-name">It</span> is running fast <span class="token comment">//它跑的很快</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>5、 疑问副词</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code><span class="token comment">// 疑问副词：引导特殊疑问句</span>
<span class="token function">how</span><span class="token punctuation">(</span>怎样<span class="token punctuation">)</span>，<span class="token function">when</span><span class="token punctuation">(</span>什么时候<span class="token punctuation">)</span>，<span class="token function">where</span><span class="token punctuation">(</span>在那里<span class="token punctuation">)</span>，<span class="token function">why</span><span class="token punctuation">(</span>为什么<span class="token punctuation">)</span>
<span class="token class-name">Where</span> are you <span class="token function">going</span><span class="token punctuation">(</span>你要去那里？<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>6、 强调副词</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code><span class="token comment">// 强调副词：强调形容词或动词</span>
<span class="token function">completely</span><span class="token punctuation">(</span>完全地<span class="token punctuation">)</span>，<span class="token function">perfectly</span><span class="token punctuation">(</span>完美地<span class="token punctuation">)</span>，<span class="token function">really</span><span class="token punctuation">(</span>真正地<span class="token punctuation">)</span>，<span class="token function">totully</span><span class="token punctuation">(</span>对极了<span class="token punctuation">)</span>，<span class="token function">mainlly</span><span class="token punctuation">(</span>主要地<span class="token punctuation">)</span>，<span class="token function">only</span><span class="token punctuation">(</span>只有<span class="token punctuation">)</span>
<span class="token class-name">A</span> really cold day <span class="token comment">// 很冷的天</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>7、 连接副词</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code><span class="token comment">// 引导主语从句，宾语从句，表语从句或并列结构</span>
<span class="token function">how</span><span class="token punctuation">(</span>怎样<span class="token punctuation">)</span>，<span class="token function">when</span><span class="token punctuation">(</span>什么时候<span class="token punctuation">)</span>，<span class="token function">where</span><span class="token punctuation">(</span>在那里<span class="token punctuation">)</span>，<span class="token function">why</span><span class="token punctuation">(</span>为什么<span class="token punctuation">)</span>，<span class="token function">then</span><span class="token punctuation">(</span>当时<span class="token punctuation">)</span>，<span class="token function">however</span><span class="token punctuation">(</span>然而<span class="token punctuation">)</span>，<span class="token function">therefore</span><span class="token punctuation">(</span>因此<span class="token punctuation">)</span>
<span class="token class-name">The</span> problem is how he can <span class="token keyword">do</span> it <span class="token comment">// 问题是他如何做这事</span>
<span class="token class-name">You</span> feel all things<span class="token punctuation">,</span> than what did you <span class="token keyword">do</span> <span class="token comment">// 我感觉到了一切，然后你做了什么</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>8、关系副词</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code><span class="token comment">// 引导定语从句</span>
when，where，why
<span class="token class-name">I</span> never forget the day when <span class="token class-name">I</span> got the award <span class="token comment">// 我永远不会忘记我获奖的那天	</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>9、 句子副词</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code><span class="token comment">// 修饰句子</span>
<span class="token function">actually</span><span class="token punctuation">(</span>实际地<span class="token punctuation">)</span>，<span class="token function">personally</span><span class="token punctuation">(</span>无理地<span class="token punctuation">)</span>，<span class="token function">certainly</span><span class="token punctuation">(</span>无疑<span class="token punctuation">)</span>，<span class="token function">definitely</span><span class="token punctuation">(</span>肯定地<span class="token punctuation">)</span>
<span class="token class-name">Actually</span><span class="token punctuation">,</span> it is more than we need <span class="token comment">// 实际上，它比我们需要的还要多</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="二、结构" tabindex="-1"><a class="header-anchor" href="#二、结构" aria-hidden="true">#</a> 二、结构</h2>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code><span class="token comment">// ly结尾的副词：大多数情况形容词+ly等于副词</span>
careful <span class="token operator">></span> carefully
beautiful <span class="token operator">></span> beautifully
important <span class="token operator">></span> importantlyf <span class="token comment">// 重要地</span>

<span class="token comment">// y结尾副词：变y为i加ly</span>
lucky <span class="token operator">></span> luckily
busy <span class="token operator">></span> busily  <span class="token comment">// 忙碌地</span>
dirty <span class="token operator">></span> dirtily <span class="token comment">// 龌龊地</span>

<span class="token comment">// wards，wise结尾的</span>
<span class="token function">inwards</span><span class="token punctuation">(</span>内向地<span class="token punctuation">)</span>，<span class="token function">eastwards</span><span class="token punctuation">(</span>向东方地<span class="token punctuation">)</span>，<span class="token function">clockwise</span><span class="token punctuation">(</span>顺时针的<span class="token punctuation">)</span>，<span class="token function">likewise</span><span class="token punctuation">(</span>同样地<span class="token punctuation">)</span>

<span class="token comment">// 本身就是ly结尾</span>
<span class="token function">ugly</span><span class="token punctuation">(</span>丑陋地<span class="token punctuation">)</span>，<span class="token function">lonely</span><span class="token punctuation">(</span>孤独地<span class="token punctuation">)</span>，<span class="token function">likely</span><span class="token punctuation">(</span>可能的<span class="token punctuation">)</span>

<span class="token comment">// 形容词和副词一样</span>
<span class="token function">hard</span><span class="token punctuation">(</span>坚固地<span class="token punctuation">)</span>，<span class="token function">late</span><span class="token punctuation">(</span>晚<span class="token punctuation">)</span>，<span class="token function">fast</span><span class="token punctuation">(</span>快速<span class="token punctuation">)</span>，<span class="token function">tight</span><span class="token punctuation">(</span>紧紧地<span class="token punctuation">)</span>

<span class="token comment">// 本身就是副词</span>
<span class="token function">so</span><span class="token punctuation">(</span>所以<span class="token punctuation">)</span><span class="token punctuation">,</span><span class="token function">very</span><span class="token punctuation">(</span>真正地<span class="token punctuation">)</span><span class="token punctuation">,</span><span class="token function">just</span><span class="token punctuation">(</span>正好<span class="token punctuation">)</span>

<span class="token comment">// 副词比较级变化，规则跟形容词比较级一样，形容词比较级特殊结构副词一样能用</span>
<span class="token comment">// 原级：A + 实意动词 + as + 副词原形 + as + B</span>
<span class="token class-name">You</span> play basketball as well as <span class="token class-name">XuKun</span> <span class="token class-name">Cai</span>  <span class="token comment">// 你篮球打的跟蔡徐坤一样好</span>
<span class="token comment">// 比较级：A + 实意动词 + 副词比较级 + than + B</span>
<span class="token class-name">I</span> know you better than she<span class="token punctuation">.</span>  <span class="token comment">// 我比她更了解你</span>
<span class="token comment">// 最高级：A + 实意动词 + the + 副词最高级 + B</span>
<span class="token class-name">Rice</span> grows the best in soil fertile<span class="token punctuation">.</span>  <span class="token comment">// 水稻在肥沃土地里生长得最好</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="三、用法" tabindex="-1"><a class="header-anchor" href="#三、用法" aria-hidden="true">#</a> 三、用法</h2>
<p>放置位置</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code>句首：why are you always late<span class="token punctuation">.</span> <span class="token comment">// 你为什么总迟到</span>
句中：<span class="token class-name">She</span> angrilly closed the door<span class="token punctuation">.</span>  <span class="token comment">// 她生气的把门关了</span>
句尾：<span class="token class-name">We</span> must work hard<span class="token punctuation">.</span> <span class="token comment">// 我们必须努力工作</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>做句子成分</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code><span class="token comment">// 作状语</span>
<span class="token class-name">Loot</span> at the photo carefully <span class="token comment">// 仔细的看这照片</span>
<span class="token comment">// 作表语</span>
<span class="token class-name">The</span> meeting is over<span class="token punctuation">.</span> <span class="token comment">// 会议结束了</span>
<span class="token comment">// 作定语</span>
<span class="token class-name">The</span> shops around are very cheap<span class="token punctuation">.</span> <span class="token comment">// 附近商店东西很便宜</span>
<span class="token comment">// 作宾补</span>
<span class="token class-name">You</span> come so late<span class="token punctuation">.</span> <span class="token comment">// 你来太晚了</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="四、易混" tabindex="-1"><a class="header-anchor" href="#四、易混" aria-hidden="true">#</a> 四、易混</h2>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code><span class="token comment">// 1、too、also、eigher、nor</span>
<span class="token comment">// too：肯定句和疑问句句尾，用逗号隔开</span>
<span class="token class-name">Are</span> you chinese<span class="token punctuation">,</span> too<span class="token operator">?</span>  <span class="token comment">// 你也是中国人</span>
<span class="token comment">// alse：肯定句的谓语动词之前，系动词后</span>
<span class="token class-name">You</span> are alse <span class="token class-name">Chinese</span><span class="token punctuation">.</span>  <span class="token comment">// 你也是中国人</span>
<span class="token comment">// eigher： 否定句句尾，用逗号隔开</span>
<span class="token class-name">I</span> am not luckly<span class="token punctuation">,</span> either<span class="token punctuation">.</span> <span class="token comment">// 我也不幸运</span>
<span class="token comment">// nor： 放句首</span>
<span class="token class-name">Nor</span> is <span class="token class-name">Peter</span> anywhere a good man<span class="token punctuation">.</span> <span class="token comment">// 皮特不是个好人</span>

<span class="token comment">// 2、sometimes，sometime，some times，some time</span>
<span class="token comment">// sometimes：有时候</span>
<span class="token class-name">Sometimes</span> <span class="token class-name">I</span> go shopping in the mall<span class="token punctuation">.</span> <span class="token comment">// 有时候我去大商场购物</span>
<span class="token comment">// sometime：未来的某个时候</span>
<span class="token class-name">Peter</span><span class="token punctuation">,</span> <span class="token class-name">I</span> will meet your mother sometime<span class="token punctuation">.</span> <span class="token comment">// 皮特，我那天去见下你的妈妈</span>
<span class="token comment">// some times:很多次(一次once，两次twice)</span>
<span class="token class-name">You</span> have treated me quite some times recently<span class="token punctuation">,</span> <span class="token class-name">Now</span> it's my turn<span class="token punctuation">.</span> 你已经请我好几次了， 这次轮到我了
<span class="token comment">// some time： 一些时间</span>
<span class="token class-name">I</span> should stay at home some time<span class="token punctuation">.</span> <span class="token comment">// 我应该呆在家一段时间时间</span>

<span class="token comment">// 3、farther、further： 表示地点距离远的时候，两个词都能用，表示更远。具体远用farther或further，抽象远用further</span>
<span class="token class-name">Can</span> we walk farther<span class="token operator">/</span>further tomorrow<span class="token operator">?</span> <span class="token comment">// 我们明天能走远点吗</span>
<span class="token class-name">See</span> under <span class="token keyword">for</span> further information<span class="token punctuation">.</span> <span class="token comment">// 更多内容详见下文</span>

<span class="token comment">// 4、most、mostly</span>
<span class="token comment">// most(名词、形容词、副词)：表示最、很、十分</span>
<span class="token class-name">The</span> most outlandish ideas<span class="token punctuation">.</span> <span class="token comment">// 最奇特的想法</span>
<span class="token comment">// mostly(副词)：表示主要的、大部分地</span>
<span class="token class-name">The</span> atoms themselves are mostly empty space<span class="token punctuation">.</span> <span class="token comment">// 原子本省大部分地空间是间隙</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


