<template><div><h2 id="一、指导思想" tabindex="-1"><a class="header-anchor" href="#一、指导思想" aria-hidden="true">#</a> 一、指导思想</h2>
<p>这几个指导思想主要的目标是让写的代码能更灵活的被其他服务调用、在扩展新功能的时候可以不用修改原来的代码、就算需要修改的时候也只需要修改极少的代码量、而且写的代码可以被重复使用。这样的代码才是好的代码。</p>
<table>
<thead>
<tr>
<th>名称</th>
<th>解释</th>
<th>描述</th>
</tr>
</thead>
<tbody>
<tr>
<td>MainTainability</td>
<td>可维护性</td>
<td>修改代码的时候，改动的越小维护性就越高</td>
</tr>
<tr>
<td>Reusability</td>
<td>可复用性</td>
<td>代码可以被重复使用</td>
</tr>
<tr>
<td>Extensibility</td>
<td>可扩展性</td>
<td>添加新功能的时候不用修改原来的代码</td>
</tr>
<tr>
<td>Flexiblity</td>
<td>灵活性</td>
<td>代码接口可以被灵活调用</td>
</tr>
</tbody>
</table>
<h2 id="二、六大原则" tabindex="-1"><a class="header-anchor" href="#二、六大原则" aria-hidden="true">#</a> 二、六大原则</h2>
<p>为了实现上面的指导思想，于是就出现了六个开发的原则。不是每个原则都需要遵守而是要视情况而定。在何时的地方用合适的原则。</p>
<p>记忆方法: 李(里)姐(接)弟(迪)易(依)开单</p>
<table>
<thead>
<tr>
<th>简称</th>
<th>名称</th>
<th>描述</th>
</tr>
</thead>
<tbody>
<tr>
<td>SRP</td>
<td>单一职责原则</td>
<td>类不能太大，不是自己负责的就不要处理</td>
</tr>
<tr>
<td>OCP</td>
<td>开闭原则</td>
<td>对扩展开放、对修改关闭。多抽象，多态是开闭原则的关键</td>
</tr>
<tr>
<td>LSP</td>
<td>里氏替换</td>
<td>子类完全可以替换父类。所有使用父类的地方都必须能透明的替换子类</td>
</tr>
<tr>
<td>DIP</td>
<td>依赖倒置</td>
<td>面向接口编程，依赖接口比依赖具体实现</td>
</tr>
<tr>
<td>ISP</td>
<td>接口隔离原则</td>
<td>接口尽量不要合二为一。将接口分为粒度更细的接口</td>
</tr>
<tr>
<td>LoD</td>
<td>迪米特法则</td>
<td>尽量不要和陌生人说话，减少其他类的耦合度</td>
</tr>
</tbody>
</table>
<h2 id="三、gof设计模式" tabindex="-1"><a class="header-anchor" href="#三、gof设计模式" aria-hidden="true">#</a> 三、GOF设计模式</h2>
<p>GoF通过实践总结了一些特定场景的设计模式。这些设计模式能很好的符合六大原则，灵活的运用这些设计模式能在开发代码的时候有不同的设计思路。这些设计模式一共有23种，一般把这些设计模式分为3类(创建型、结构型、行为型)，创建型关注对象的创建过程，结构型关注对象的组成方式，行为型关注对象之间的通信</p>
<table>
<thead>
<tr>
<th>名称</th>
<th>关注点</th>
<th>例子</th>
</tr>
</thead>
<tbody>
<tr>
<td>创建型</td>
<td>对象的创建过程</td>
<td>建造者、单例、工厂、抽象工厂、原型</td>
</tr>
<tr>
<td>结构型</td>
<td>对象的组合过程</td>
<td>外观、装饰、适配器、桥接、组合、享元、代理</td>
</tr>
<tr>
<td>行为型</td>
<td>对象的通信</td>
<td>策略、模版方法、中介者、备忘录、观察者、命令、责任链、解释器、迭代器、状态、访问者</td>
</tr>
</tbody>
</table>
<h2 id="四、具体" tabindex="-1"><a class="header-anchor" href="#四、具体" aria-hidden="true">#</a> 四、具体</h2>
<h3 id="_4-1-创建型" tabindex="-1"><a class="header-anchor" href="#_4-1-创建型" aria-hidden="true">#</a> 4.1 创建型</h3>
<table>
<thead>
<tr>
<th>名称</th>
<th>描述</th>
<th>场景</th>
</tr>
</thead>
<tbody>
<tr>
<td>单例</td>
<td>系统中只存在一份</td>
<td>spring的bean默认单例</td>
</tr>
<tr>
<td>工厂</td>
<td>通过工厂生产不同的类，屏蔽创建过程</td>
<td>spring的bean工厂</td>
</tr>
<tr>
<td>抽象工厂</td>
<td>利用抽象工厂类创建工厂，创建过程交给过工厂类完成</td>
<td>定义一系列的产品族</td>
</tr>
<tr>
<td>建造者</td>
<td>需求变化的时候对象也跟着变化，通过不同的算法构建复杂的对象</td>
<td>构建一个复杂对象</td>
</tr>
<tr>
<td>原型</td>
<td>复制新类时（浅clone和深clone问题）</td>
<td>java clone</td>
</tr>
</tbody>
</table>
<h3 id="_4-2-结构型" tabindex="-1"><a class="header-anchor" href="#_4-2-结构型" aria-hidden="true">#</a> 4.2 结构型</h3>
<table>
<thead>
<tr>
<th>名称</th>
<th>描述</th>
<th>场景</th>
</tr>
</thead>
<tbody>
<tr>
<td>外观</td>
<td>将多个类放在一个方法里面调用</td>
<td>接口多、调用复杂、需要统一调用时</td>
</tr>
<tr>
<td>装饰</td>
<td>选择不同的类可以组合出不同的功能</td>
<td>动态的给类添加职责时</td>
</tr>
<tr>
<td>适配器</td>
<td>类之间的适配过程，就行3孔插座转2孔插座</td>
<td>两个类之间需要转换时</td>
</tr>
<tr>
<td>桥接</td>
<td>将抽象和实现解耦，是他们可以独立变化</td>
<td>系统多角度分类，每个角度都可能变化</td>
</tr>
<tr>
<td>组合</td>
<td>自己的属性就是自己，利用递归进行解析</td>
<td>树形结构数据展示</td>
</tr>
<tr>
<td>享元</td>
<td>为了减少实例化的次数，利用共享对象的方式</td>
<td>线程池的池化思想</td>
</tr>
<tr>
<td>代理</td>
<td>添加一个中间层用一个类代替另一个的功能</td>
<td>动/静代理，cjlib、jdk自动的动态代理</td>
</tr>
</tbody>
</table>
<h3 id="_4-3-行为型" tabindex="-1"><a class="header-anchor" href="#_4-3-行为型" aria-hidden="true">#</a> 4.3 行为型</h3>
<table>
<thead>
<tr>
<th>名称</th>
<th>描述</th>
<th>场景</th>
</tr>
</thead>
<tbody>
<tr>
<td>策略</td>
<td>一个类的行为在运行时根据不同的策略进行更改</td>
<td>扩展其他策略不需要修改之前的代码。comparator</td>
</tr>
<tr>
<td>模版方法</td>
<td>将一些通用的方法放在一起</td>
<td>每次都需要执行很多相同代码时</td>
</tr>
<tr>
<td>中介者</td>
<td>用星形接口改善调用的复杂度</td>
<td>类与类之间耦合特别严重时。消息中间件</td>
</tr>
<tr>
<td>备忘录</td>
<td>记录状态用于回滚，把内部状态记录在外部</td>
<td>需要记录操作备忘时</td>
</tr>
<tr>
<td>观察者</td>
<td>需要观察一个对象发生改变时做相应处理时</td>
<td>mq、目标类发生改变通知所有观察者</td>
</tr>
<tr>
<td>命令</td>
<td>通过数据驱动行为，不同的命令执行不同的操作</td>
<td>有命令的地方</td>
</tr>
<tr>
<td>责任链</td>
<td>多个对象处理同一个数据形成链条式结构</td>
<td>日志、filter</td>
</tr>
<tr>
<td>解释器</td>
<td>用于解释一种语言</td>
<td>语法需要解释的场景</td>
</tr>
<tr>
<td>迭代器</td>
<td>一个顺序访问容器元素的方法，一种多态的应用</td>
<td>Iterator</td>
</tr>
<tr>
<td>状态</td>
<td>内部状态的改变，其行为也跟着改变</td>
<td>条件、分支语句的代替者</td>
</tr>
<tr>
<td>访问者</td>
<td>执行的逻辑跟着访问者的改变而改变</td>
<td>需要对类进行很多不相关的操作，需要避免操作污染这个类时</td>
</tr>
</tbody>
</table>
<h3 id="五、总结" tabindex="-1"><a class="header-anchor" href="#五、总结" aria-hidden="true">#</a> 五、总结</h3>
<p>设计模式是在特定场景的一些优秀的设计方式，灵活的使用这些设计模式，能在开发代码的时候有更多选择思路。很多的设计模式都是相通的，没必要在写代码的时候生硬的套用这些设计模式。可以在实际代码开发中使用多种方式实现自己的业务逻辑。</p>
</div></template>


